local cdb = require("lucdb")

describe("cdb", function()
	it("should dislike filenames with zeroes", function()
		assert.has.error(function()
			cdb.writer("oh n\0")
		end)
	end)

	it("should write stuff", function()
		local writer = cdb.writer("test.cdb")
		writer:add("abc", "123")
		writer:add("abc", "123")
		writer:add("abc", "456")
		writer:add("d\0ef", "c\0\0l")
		writer:close()
	end)

	it("should read stuff", function()
		local reader = cdb.reader("test.cdb")

		assert.are.same(3, reader:count("abc"))
		assert.are.same("123", reader:get("abc"))
		assert.are.same("123", reader:get("abc", 1))
		assert.are.same("123", reader:get("abc", 2))
		assert.are.same("456", reader:get("abc", 3))
		assert.are.same(false, reader:get("abc", 4))
		assert.are.same({"123", "123", "456"}, reader:get_all("abc"))

		assert.are.same(1, reader:count("d\0ef"))
		assert.are.same("c\0\0l", reader:get("d\0ef"))
		assert.are.same({"c\0\0l"}, reader:get_all("d\0ef"))

		assert.are.same(false, reader:get("none"))
		assert.are.same({}, reader:get_all("none"))
		reader:close()
	end)

	it("should dislike record numbers <1", function()
		local reader = cdb.reader("test.cdb")
		assert.has.error(function() reader:get("abcd", -1) end)
		assert.has.error(function() reader:get("abcd",  0) end)
		reader:close()
	end)

	it("should iterate over stuff", function()
		local reader = cdb.reader("test.cdb")
		local s = spy.new()
		assert.are.same(true, reader:foreach(function(...) s(...) end))
		assert.spy(s).was.called(4)
		assert.spy(s).was.called.with("abc", "123")
		assert.spy(s).was.called.with("abc", "456")
		assert.spy(s).was.called.with("d\0ef", "c\0\0l")

		reader:close()
	end)

	it("should allow errors while iterating", function()
		local reader = cdb.reader("test.cdb")

		assert.has.error(function()
			reader:foreach(function()
				error("oh no!")
			end)
		end)
	end)

	it("should let a closed object be closed again as a no-op", function()
		local reader = cdb.reader("test.cdb")
		reader:close()
		assert.has.no.error(function()
			reader:close()
		end)
	end)

	it("should correctly report whether objects are open or not", function()
		local reader = cdb.reader("test.cdb")
		assert.is_true(reader:is_open())
		reader:close()
		assert.is_false(reader:is_open())
	end)

	it("should correctly report handles' modes", function()
		local reader = cdb.reader("tmp.cdb")
		assert.are.same("read-only", reader:get_mode())
		reader:close()

		local writer = cdb.writer("tmp.cdb")
		assert.are.same("read-write", writer:get_mode())
		writer:close()
	end)

	it("should correctly return a custom type", function()
		local reader = cdb.reader("test.cdb")
		assert.are.same("lucdb.handle", cdb.type(reader))
		assert.is_nil(cdb.type({}))
		assert.is_nil(cdb.type(""))
		assert.is_nil(cdb.type())
		reader:close()
	end)

	it("should stringify handles nicely", function()
		local reader = cdb.reader("test.cdb")
		assert.matches("<lucdb%.handle read%-only open>: 0x%x+", tostring(reader))
		reader:close()
		assert.matches("<lucdb%.handle read%-only closed>: 0x%x+", tostring(reader))

		local writer = cdb.writer("tmp.cdb")
		assert.matches("<lucdb%.handle read%-write open>: 0x%x+", tostring(writer))
		writer:close()
		assert.matches("<lucdb%.handle read%-write closed>: 0x%x+", tostring(writer))
	end)

	it("should allow different word sizes", function()
		local writer16 = cdb.writer("test16.cdb", { word_size = 16 })
		writer16:add("abcd", "1234")
		writer16:close()

		local reader16 = cdb.reader("test16.cdb", { word_size = 16 })
		assert.are.same({"1234"}, reader16:get_all("abcd"))
		reader16:close()

		assert.is_nil(cdb.reader("test16.cdb"))
		assert.is_nil(cdb.reader("test16.cdb", { word_size = 64 }))
	end)

	it("should dislike invalid word sizes", function()
		assert.has.error(function()
			cdb.writer("test16.cdb", { word_size = 1 })
		end, "word_size must be one of 0, 16, 32 or 64 (got 1)")
		assert.has.error(function()
			cdb.writer("test16.cdb", { word_size = -16 })
		end, "word_size must be one of 0, 16, 32 or 64 (got -16)")
		assert.has.error(function()
			cdb.writer("test16.cdb", { word_size = 128 })
		end, "word_size must be one of 0, 16, 32 or 64 (got 128)")
	end)
end)
