local cdb = require("lucdb")

describe("cdb", function()
	it("should dislike filenames with zeroes", function()
		assert.has.error(function()
			cdb.writer("oh n\0")
		end)
	end)

	it("should write stuff", function()
		local writer = cdb.writer("test.cdb")
		writer:insert("abc", "123")
		writer:insert("abc", "123")
		writer:insert("abc", "456")
		writer:insert("d\0ef", "c\0\0l")
		writer:close()
	end)

	it("should read stuff", function()
		local reader = cdb.reader("test.cdb")

		assert.are.same(3, reader:count("abc"))
		assert.are.same("123", reader:get("abc"))
		assert.are.same("123", reader:get("abc", 1))
		assert.are.same("123", reader:get("abc", 2))
		assert.are.same("456", reader:get("abc", 3))
		assert.are.same(false, reader:get("abc", 4))
		assert.are.same({"123", "123", "456"}, reader:get_all("abc"))

		assert.are.same(1, reader:count("d\0ef"))
		assert.are.same("c\0\0l", reader:get("d\0ef"))
		assert.are.same({"c\0\0l"}, reader:get_all("d\0ef"))

		assert.are.same(false, reader:get("none"))
		assert.are.same({}, reader:get_all("none"))
		reader:close()
	end)

	it("should dislike record numbers <1", function()
		local reader = cdb.reader("test.cdb")
		assert.has.error(function() reader:get("abcd", -1) end)
		assert.has.error(function() reader:get("abcd",  0) end)
		reader:close()
	end)

	it("should iterate over stuff", function()
		local reader = cdb.reader("test.cdb")
		local s = spy.new()
		assert.are.same(true, reader:foreach(function(...) s(...) end))
		assert.spy(s).was.called(4)
		assert.spy(s).was.called.with("abc", "123")
		assert.spy(s).was.called.with("abc", "456")
		assert.spy(s).was.called.with("d\0ef", "c\0\0l")

		reader:close()
	end)

	it("should allow errors while iterating", function()
		local reader = cdb.reader("test.cdb")

		assert.has.error(function()
			reader:foreach(function()
				error("oh no!")
			end)
		end)
	end)

	it("should let a closed object be closed again as a no-op", function()
		local reader = cdb.reader("test.cdb")
		reader:close()
		assert.has.no.error(function()
			reader:close()
		end)
	end)
end)
